# fly.toml app configuration file generated for conectados-tp-dds on 2023-11-23T19:10:26-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "conectados-tp-dds"
primary_region = "eze"

[build]

[http_service]
  internal_port = 9001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
